### ISSUE TITLE
Privacy compliant tracking

### ISSUE THREAD

**Issue by webbertakken** [game-ci/documentation#280]
We've recently introduced GA4. We use it to learn how our website is used.

We'll keep track of measures we're taking or still have to take to make tracking compliant.
Note that we have no intention of tracking any personally identifiable information.

From this [guide](https://taginspector.com/articles/google-analytics-4-ga4-compliant-tracking-guide/#elementor-toc__heading-anchor-0) I understand the following:

**ePrivacy Directive (EU “Cookie Laws”)**

- [ ] Don't store _any_ cookie without consent.

**General Data Protection Regulation (GDPR)**

- Don't track _any_ personal information without 
  1. providing the purpose 
  2. having consent

It is possible to not track personally identifiable information (PII) at all.
Some features need to be configured for that:
  - [x] disable Google signals data collection (get started button means it's disabled)
![image](https://user-images.githubusercontent.com/20756439/169381945-663e3698-9a3e-4367-ba02-e5965b239527.png)
  - [x] disable Ads Personalisation
![image](https://user-images.githubusercontent.com/20756439/169382122-eba20675-7ec4-469c-a9fa-34c87a5e320e.png)
  - [x] Disable collection of user ip addresses (configured in Google Tag Manager)
![image](https://user-images.githubusercontent.com/20756439/169384045-dafe7009-e2aa-4fbf-b324-139649fff43a.png)

**Comment by webbertakken** [comment]
Any tracking experts in the community? Let me know if I'm somehow far off. It's a lot of information to sift through.

Ideas about how to most elegantly implement a cookie consent would be great. We use the [docusaurus gtm plugin](https://github.com/LukasGentele/docusaurus-gtm-plugin) (not hard to understand)
